config/routes.rb
WarlocksRemake::Application.routes.draw do
  get "game/test"
  post "game/test"
  post "game/resettest"
  get "spells/index"
  get "player/new"
  get "game/index"
  get "game/show"
  get "game/new"
  resources :information_pages

  get "information_page/home"
  root "information_page#home"

end

app/models/effect.rb
class Effect < ActiveRecord::Base
  belongs_to :target
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/hand_move.rb
class HandMove < ActiveRecord::Base
end

app/models/information_page.rb
class InformationPage < ActiveRecord::Base
end

app/models/noob.rb
class Noob < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/player_move.rb
class PlayerMove < ActiveRecord::Base
end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
  belongs_to :spell, :class_name => "Spell"
  def self.possible_moves(hand_gestures, support_gestures)
    gestures = ['D','P','W','S','F']
    spells = []
    Sequence.all.each do |seq|
      comparedportion = Regexp.new(seq.sequence[0..-2].upcase + "$")
      #calculate support hand
      supporthand = Regexp.new(seq.sequence[0..-2].gsub(/[A-Z]/, ".").upcase + "$")
      if comparedportion.match(hand_gestures) != nil && supporthand.match(support_gestures) != nil
        ges = seq.sequence[-1]
        spells << ges + " - " + seq.spell.name + " (" + seq.sequence + ")"
      end
    end
    spells
  end
  #returns both regex to search for both spells
  #def self.hand_regex
  #returns whether the spell matches the given hands
  # # provides a wildcard
  #def self.spell_match(hand_gestures, 
end

app/models/spell.rb
class Spell < ActiveRecord::Base
  has_many :sequences
end

app/models/target.rb
class Target < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "application"
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def test
    #reset the session to the defaults
    if params[:move] == nil
      set_game_beginning
    else
      
      session[session[:player]][:move] = params[:move]
      #switch between players
      if session[:player] == nil or session[:player] == :player1
        session[:player] = :player0
      elsif session[:player] == :player0
        session[:player] = :player1
      end
    end
    if turn_complete
      update_game
      reset_move_input
    end
    push_session
  end
  def resettest
    redirect_to game_test_path
  end
  def update_game
    session[:players].each do |player|
      [:left_hand, :right_hand].each do |hand|
        session[player][hand] << session[player][:move][hand][0].upcase
        session
      end
    end
    
  end
  def cast_spell(spell_name)

  end
  #push the variables in the session to the parameters
  def push_session
    session[:players].each do |player|
      params[player] = Hash.new()
      [:left_hand, :right_hand].each do |hand|
        params[player][hand] = session[player][hand]
      end
    end
  end
  def turn_complete
    session[:player0][:move] != nil and session[:player1][:move] != nil
  end
  def reset_move_input
    session[:player0][:move] = nil
    session[:player1][:move] = nil
    session[:player] = :player0
  end
  #set default state for the beginning of a game
  def set_game_beginning
    reset_session
    params[:move] = Hash.new()
    params[:move][:left_hand] = ""
    params[:move][:right_hand] = ""
    session[:players] = [:player0, :player1]
    session[:player] = :player0
    session[:players].each do |player|
      session[player] = Hash.new()
      session[player][:health] = 15
      [:left_hand, :right_hand].each do |hand|
        session[player][hand] = "B"
      end
    end
    
  end
end

app/controllers/information_page_controller.rb
class InformationPageController < ApplicationController
  def home
    
  end
  def index
    
  end
end

app/controllers/information_pages_controller.rb
class InformationPagesController < ApplicationController
  before_action :set_information_page, only: [:show, :edit, :update, :destroy]

  # GET /information_pages
  # GET /information_pages.json
  def index
    @information_pages = InformationPage.all
  end

  # GET /information_pages/1
  # GET /information_pages/1.json
  def show
  end

  # GET /information_pages/new
  def new
    @information_page = InformationPage.new
  end

  # GET /information_pages/1/edit
  def edit
  end

  # POST /information_pages
  # POST /information_pages.json
  def create
    @information_page = InformationPage.new(information_page_params)

    respond_to do |format|
      if @information_page.save
        format.html { redirect_to @information_page, notice: 'Information page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @information_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @information_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information_pages/1
  # PATCH/PUT /information_pages/1.json
  def update
    respond_to do |format|
      if @information_page.update(information_page_params)
        format.html { redirect_to @information_page, notice: 'Information page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @information_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information_pages/1
  # DELETE /information_pages/1.json
  def destroy
    @information_page.destroy
    respond_to do |format|
      format.html { redirect_to information_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information_page
      @information_page = InformationPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_page_params
      params[:information_page]
    end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def new
  end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def hand_move_list(player, hand, support_hand)
    ['>', 'C', 'D','P','W','S','F'] +
	 Sequence.possible_moves(params[player][hand], params[player][support_hand])
    #params[session[:player]][:left_hand]
    #session[:player0][:left_hand]
  end
end

app/helpers/information_page_helper.rb
module InformationPageHelper
end

app/helpers/information_pages_helper.rb
module InformationPagesHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/game/test.html.haml
%h1 Play a game
-session[:players].each do |player|
  =player
  =session[player][:health]
  %table#moves
    %tr
      - params[player][:left_hand].split("").each do |letter|
        %td=letter
    %tr
      - params[player][:right_hand].split("").each do |letter|
        %td=letter
  %br

=session[:player]

=params[:move][:left_hand]
=params[:move][:right_hand]
%br
test
=params[:player1][:left_hand]
=form_tag game_test_path do

  ='Left Hand:'
  = select :move, :left_hand, hand_move_list(session[:player], :left_hand, :right_hand)
  %br
  ='Right Hand:'
  = select :move, :right_hand, hand_move_list(session[:player], :right_hand, :left_hand)
  %br
  =submit_tag "Submit move"


=form_tag game_resettest_path do
  =submit_tag "Reset game"

app/views/information_page/home.html.haml
%h1 Welcome to the Warlocks Remake game!
%p
  %h3
    This is an attempt to remake the game Spellbinder, invented by Richard Bartle.
    It is mostly based on the Warlocks Free to Play game at the ravenblack website.
%h1 Current state
Currently I am prototyping the user interface.  I would appreciate it if you looked through the website and gave me some feedback on the page.
%h1
%p For people new to warlocks, the game rules can be found here:
= link_to 'http://games.ravenblack.net/rules/0/index.html', 'http://games.ravenblack.net/rules/0/index.html'

app/views/information_pages/_form.html.erb
<%= form_for(@information_page) do |f| %>
  <% if @information_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information_page.errors.count, "error") %> prohibited this information_page from being saved:</h2>

      <ul>
      <% @information_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/information_pages/edit.html.erb
<h1>Editing information_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @information_page %> |
<%= link_to 'Back', information_pages_path %>

app/views/information_pages/index.html.erb
<h1>Listing information_pages</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @information_pages.each do |information_page| %>
      <tr>
        <td><%= link_to 'Show', information_page %></td>
        <td><%= link_to 'Edit', edit_information_page_path(information_page) %></td>
        <td><%= link_to 'Destroy', information_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Information page', new_information_page_path %>

app/views/information_pages/new.html.erb
<h1>New information_page</h1>

<%= render 'form' %>

<%= link_to 'Back', information_pages_path %>

app/views/information_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_information_page_path(@information_page) %> |
<%= link_to 'Back', information_pages_path %>

app/views/player/new.html.haml
%h1 Register for an account
%br
=label :player, :username, "Username: "
=text_field :username, 'username'
%br
=label :password, :password, 'Password: '
=password_field :password, 'password'
%br
=label :retype_password, :retype_password, 'Retype Password: '
=password_field :retype_password, 'retype_password'
%br
=label :email, :email, 'Email: '
=text_field :email, 'email'
%br
=submit_tag 'Register'

app/views/spells/index.html.erb
<h1>Spells#index</h1>
<p>Find me in app/views/spells/index.html.erb</p>